
import { Listing, ListingType, Status, Event, i18nContent } from './types';

export const TRANSLATIONS: i18nContent = {
  hero_title: { en: "Visit Gondar", am: "ጎንደርን ይጎብኙ" },
  hero_subtitle: { en: "The Camelot of Africa", am: "የአፍሪካ ካሜሎት" },
  search_placeholder: { en: "Search hotels, attractions, cafés...", am: "ሆቴሎችን፣ መስህቦችን፣ ካፌዎችን ይፈልጉ..." },
  explore: { en: "Explore", am: "ይመርምሩ" },
  attractions: { en: "Attractions", am: "መስህቦች" },
  hotels: { en: "Hotels & Resorts", am: "ሆቴሎች እና ሪዞርቶች" },
  restaurants: { en: "Restaurants & Cafés", am: "ምግብ ቤቶች እና ካፌዎች" },
  events: { en: "Events", am: "ክስተቶች" },
  map: { en: "Interactive Map", am: "ካርታ" },
  timket_guide: { en: "Timket Guide", am: "የጥምቀት መመሪያ" },
  featured_attractions: { en: "Top Attractions", am: "ዋና ዋና መስህቦች" },
  best_hotels: { en: "Best Hotels", am: "ምርጥ ሆቴሎች" },
  upcoming_events: { en: "Upcoming Events", am: "የሚመጡ ክስተቶች" },
  view_all: { en: "View All", am: "ሁሉንም ይመልከቱ" },
  details: { en: "Details", am: "ዝርዝሮች" },
  directions: { en: "Directions", am: "አቅጣጫዎች" },
  call: { en: "Call", am: "ይደውሉ" },
  whatsapp: { en: "WhatsApp", am: "ዋትስአፕ" },
  visit_website: { en: "Visit Website", am: "ድህረ ገጽ" },
  book_now: { en: "Book Now", am: "አሁኑኑ ይያዙ" },
  admin_login: { en: "Admin Login", am: "የአስተዳዳሪ መግቢያ" },
  nearby: { en: "Nearby", am: "አቅራቢያ" },
  history: { en: "History & Tips", am: "ታሪክ እና ምክሮች" },
  visiting_info: { en: "Visiting Info", am: "የጉብኝት መረጃ" },
  open_hours: { en: "Open Hours", am: "የስራ ሰዓት" },
  entry_fee: { en: "Entry Fee", am: "የመግቢያ ክፍያ" },
};

export const MOCK_LISTINGS: Listing[] = [
  // --- ATTRACTIONS ---
  {
    id: 'attr-1',
    type: ListingType.ATTRACTION,
    name_en: 'Fasil Ghebbi (Royal Enclosure)',
    name_am: 'ፋሲል ግቢ',
    desc_en: 'UNESCO World Heritage fortress-city containing six main castles.',
    desc_am: 'በዩኔስኮ የተመዘገበ ታሪካዊ የቤተ መንግስት ግቢ።',
    details_en: 'Fasil Ghebbi is Gondar’s star attraction – a walled fortress-city that was the seat of Ethiopian emperors in the 1600s and 1700s. Enclosed by a 900-meter-long stone wall, it contains six main castles, palaces, churches, libraries, and stables built by Emperor Fasilides and his successors. The architecture is uniquely eclectic, blending Hindu, Arab, and Baroque influences.',
    details_am: 'ፋሲል ግቢ በ17ኛው እና በ18ኛው ክፍለ ዘመን በአፄ ፋሲለደስ እና ተከታዮቻቸው የተገነባ የቤተ መንግስት ግቢ ነው። የአውሮፓ፣ የአረብ እና የህንድ ስልጣኔዎች ቅይጥ የሆነ ልዩ የስነ-ህንፃ ጥበብ ይታይበታል።',
    lat: 12.6072,
    lng: 37.4695,
    address_en: 'City Center, Gondar',
    address_am: 'መሀል ከተማ፣ ጎንደር',
    area: 'City Center',
    featured: true,
    status: Status.PUBLISHED,
    category: 'Castle',
    image_url: 'https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&w=800&q=80',
    created_at: new Date().toISOString()
  },
  {
    id: 'attr-2',
    type: ListingType.ATTRACTION,
    name_en: 'Fasilides’ Bath (Timkete Bahir)',
    name_am: 'ፋሲለደስ መዋኛ',
    desc_en: 'A 17th-century ceremonial pool and royal retreat.',
    desc_am: 'ለጥምቀት በዓል ማክበሪያነት የሚያገለግል ታሪካዊ መዋኛ።',
    details_en: 'Across town lies Fasilides’ Bath – a ceremonial pool and small castle structure set amid tranquil banyan trees. Every January, the pool is filled with water for the Timket (Epiphany) celebrations, where thousands gather for the reenactment of Jesus’s baptism.',
    details_am: 'ከከተማው በስተ ደቡብ ምዕራብ የሚገኝ እና ለጥምቀት በዓል በድምቀት የሚያገለግል ታሪካዊ ስፍራ ነው።',
    lat: 12.6110,
    lng: 37.4580,
    address_en: 'Southwest Gondar',
    address_am: 'ጎንደር ደቡብ ምዕራብ',
    area: 'Piazza Area',
    featured: true,
    status: Status.PUBLISHED,
    category: 'History',
    image_url: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80',
    created_at: new Date().toISOString()
  },
  {
    id: 'attr-3',
    type: ListingType.ATTRACTION,
    name_en: 'Debre Berhan Selassie Church',
    name_am: 'ደብረ ብርሃን ሥላሴ ቤተክርስቲያን',
    desc_en: 'Famous for its vivid frescoes and angel-painted ceiling.',
    desc_am: 'በመላእክት ስዕሎች የተሸለመ ጣራ ያለው ታዋቂ ቤተክርስቲያን።',
    details_en: 'Renowned for its stunning interior artwork, this 17th-century church features hundreds of winged angel faces painted on the ceiling. Legend says a swarm of bees once protected it from invaders. It is often considered the most beautiful church in Ethiopia.',
    details_am: 'በአፄ ኢያሱ ዳግማዊ የተገነባው ይህ ቤተክርስቲያን በውስጠኛው ክፍል ባሉ ድንቅ የመላእክት ስዕሎች ይታወቃል።',
    lat: 12.6105,
    lng: 37.4764,
    address_en: 'North of Fasil Ghebbi',
    address_am: 'ከፋሲል ግቢ በስተሰሜን',
    area: 'City Center',
    featured: true,
    status: Status.PUBLISHED,
    category: 'Church',
    image_url: 'https://images.unsplash.com/photo-1540553016722-983e48a2cd10?auto=format&fit=crop&w=800&q=80',
    created_at: new Date().toISOString()
  },
  {
    id: 'attr-4',
    type: ListingType.ATTRACTION,
    name_en: 'Kuskuam Complex',
    name_am: 'ቁስቁዋም ማርያም',
    desc_en: 'Ruined palace and church of Empress Mentewab on a hill.',
    desc_am: 'የእቴጌ ምንትዋብ የቤተ መንግስት ቅሪት።',
    details_en: 'A peaceful royal compound perched on a hill, Kuskuam was the residence of the influential Empress Mentewab in the 18th century. It offers panoramic views and houses artifacts from her era.',
    details_am: 'ከከተማዋ በስተ ምዕራብ የሚገኝ እና ከተማዋን ቁልቁል ለማየት የሚረዳ ስፍራ።',
    lat: 12.6201,
    lng: 37.4452,
    address_en: 'Kuskuam Hill',
    address_am: 'ቁስቁዋም ኮረብታ',
    area: 'Outskirts',
    featured: false,
    status: Status.PUBLISHED,
    category: 'Palace',
    image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    created_at: new Date().toISOString()
  },
  {
    id: 'attr-5',
    type: ListingType.ATTRACTION,
    name_en: 'Woleka (Falasha Village)',
    name_am: 'ወለካ (የፈላሻ መንደር)',
    desc_en: 'Historical home of the Beta Israel Jewish community.',
    desc_am: 'የኢትዮጵያ አይሁዳውያን ታሪካዊ መንደር።',
    details_en: 'Located north of Gondar, Woleka was historically the village of Ethiopian Jews known for skilled craftsmanship in pottery and weaving. Today, visitors explore ruins and buy local handicrafts.',
    details_am: 'በባህል እና በታሪክ የሚታወቅ የታወቀ የጎንደር ክፍል ነው።',
    lat: 12.6333,
    lng: 37.4667,
    address_en: 'North of Gondar',
    address_am: 'ከጎንደር በስተሰሜን',
    area: 'North Gondar',
    featured: false,
    status: Status.PUBLISHED,
    category: 'Village',
    image_url: 'https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?auto=format&fit=crop&w=800&q=80',
    created_at: new Date().toISOString()
  },
  {
    id: 'attr-6',
    type: ListingType.ATTRACTION,
    name_en: 'Saturday Market (Kidame Gebya)',
    name_am: 'ቅዳሜ ገበያ',
    desc_en: 'Authentic open-air market experience for local culture.',
    desc_am: 'ባህላዊ የጎንደር ቅዳሜ ገበያ።',
    details_en: 'The biggest day at Gondar\'s open-air market is Saturday. Vendors from surrounding villages sell fresh produce, spices, coffee, handmade pottery, and traditional clothing.',
    details_am: 'ባህላዊ የንግድ ልውውጥ የሚታይበት የከተማዋ ትልቁ ገበያ።',
    lat: 12.6070,
    lng: 37.4680,
    address_en: 'Market Area',
    address_am: 'ገበያ አካባቢ',
    area: 'City Center',
    featured: false,
    status: Status.PUBLISHED,
    category: 'Market',
    image_url: 'https://images.unsplash.com/photo-1488459711626-47dfab2136f7?auto=format&fit=crop&w=800&q=80',
    created_at: new Date().toISOString()
  },

  // --- HOTELS ---
  {
    id: 'h-1',
    type: ListingType.HOTEL,
    name_en: 'Gondar Hills Resort',
    name_am: 'ጎንደር ሂልስ ሪዞርት',
    desc_en: 'Upscale resort with 78 suites and panoramic terrace views.',
    desc_am: 'አስደናቂ እይታ ያለው ዘመናዊ ሪዞርት።',
    details_en: 'A modern luxury hotel perched on the hills, Gondar Hills Resort boasts 78 upscale suites and a terrace with views of the castles and valleys.',
    details_am: 'ከተማዋን ቁልቁል የሚመለከት እጅግ ዘመናዊ ሆቴል።',
    lat: 12.6220,
    lng: 37.4810,
    address_en: 'Hillside, Gondar',
    address_am: 'ጎንደር ሂልስ',
    area: 'Hillside',
    featured: true,
    status: Status.PUBLISHED,
    price_level: '$$$',
    amenities: ['Suites', 'Terrace', 'Restaurant', 'Spa'],
    image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    created_at: new Date().toISOString()
  },
  {
    id: 'h-2',
    type: ListingType.HOTEL,
    name_en: 'Goha Hotel',
    name_am: 'ጎሃ ሆቴል',
    desc_en: 'Hilltop hotel serving guests for decades with charm.',
    desc_am: 'ከተማዋን በሚገባ የሚያሳይ ታዋቂ ሆቴል።',
    details_en: 'Famous for its stunning views from the terrace, Goha Hotel has been a mid-range favorite for decades, offering traditional Ethiopian charm and reliable service.',
    details_am: 'በባህላዊ እይታው እና በጥሩ አገልግሎቱ የሚታወቅ ሆቴል።',
    lat: 12.6033,
    lng: 37.4740,
    address_en: 'North of Piazza',
    address_am: 'ከፒያሳ በስተሰሜን',
    area: 'Hillside',
    featured: true,
    status: Status.PUBLISHED,
    price_level: '$$',
    amenities: ['Terrace', 'Traditional Food', 'Wi-Fi'],
    image_url: 'https://images.unsplash.com/photo-1551882547-ff43c63efe5c?auto=format&fit=crop&w=800&q=80',
    created_at: new Date().toISOString()
  },
  {
    id: 'h-3',
    type: ListingType.HOTEL,
    name_en: 'Haile Resort Gondar',
    name_am: 'ኃይሌ ሪዞርት ጎንደር',
    desc_en: 'Modern amenities and pool near the Royal Enclosure.',
    desc_am: 'ከፋሲል ግቢ አቅራቢያ የሚገኝ ዘመናዊ ሪዞርት።',
    details_en: 'Part of the Haile Resorts chain, it offers 66 rooms, a swimming pool, spa, and restaurant, all conveniently located near the city center.',
    details_am: 'ዋና ዋና ታሪካዊ ቦታዎች አቅራቢያ የሚገኝ ምርጥ ሆቴል።',
    lat: 12.6085,
    lng: 37.4650,
    address_en: 'City Center',
    address_am: 'መሀል ከተማ',
    area: 'City Center',
    featured: true,
    status: Status.PUBLISHED,
    price_level: '$$$',
    amenities: ['Pool', 'Spa', 'Gym', 'Restaurant'],
    image_url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
    created_at: new Date().toISOString()
  },
  {
    id: 'h-4',
    type: ListingType.HOTEL,
    name_en: 'Inn of the Four Sisters',
    name_am: 'አራቱ እህትማማቾች ግስት ሃውስ',
    desc_en: 'Budget-friendly guesthouse with warm hospitality.',
    desc_am: 'ምርጥ አገልግሎት የሚሰጥ የእንግዳ ማረፊያ።',
    details_en: 'A cozy, budget-friendly inn linked to the famous restaurant. Known for simple, comfortable rooms and a welcoming courtyard filled with culture.',
    details_am: 'ለእንግዶች ምቹ እና ቀለል ያለ ዋጋ ያለው ማረፊያ።',
    lat: 12.6090,
    lng: 37.4720,
    address_en: 'Near Castles',
    address_am: 'ፋሲል ግቢ አጠገብ',
    area: 'City Center',
    featured: false,
    status: Status.PUBLISHED,
    price_level: '$',
    amenities: ['Wi-Fi', 'Breakfast', 'Cultural Decor'],
    image_url: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=800&q=80',
    created_at: new Date().toISOString()
  },

  // --- FOOD ---
  {
    id: 'r-1',
    type: ListingType.RESTAURANT,
    name_en: 'Four Sisters Restaurant',
    name_am: 'አራቱ እህትማማቾች ምግብ ቤት',
    desc_en: 'Must-visit for authentic Amhara cuisine and cultural shows.',
    desc_am: 'በባህላዊ ምግቦች እና ዝግጅቶች የታወቀ።',
    details_en: 'Gondar’s most famous eatery. Famous for dishes like doro wat and evening cultural dance performances. The staff often host coffee ceremonies after dinner.',
    details_am: 'ምርጥ የኢትዮጵያ ምግቦች የሚቀርቡበት ተወዳጅ ስፍራ።',
    lat: 12.6080,
    lng: 37.4710,
    address_en: 'Gondar Center',
    address_am: 'ጎንደር መሀል',
    area: 'City Center',
    featured: true,
    status: Status.PUBLISHED,
    price_level: '$$',
    amenities: ['Traditional Music', 'Coffee Ceremony', 'Garden Seating'],
    image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    created_at: new Date().toISOString()
  },
  {
    id: 'r-2',
    type: ListingType.RESTAURANT,
    name_en: 'Habesha Coffee & Cafe',
    name_am: 'ሀበሻ ቡና እና ካፌ',
    desc_en: 'The place for traditional coffee ceremonies and macchiatos.',
    desc_am: 'ምርጥ ቡና እና የቡና ስነ-ስርዓት የሚታይበት።',
    details_en: 'Popular among locals and tourists for traditional coffee ceremonies where beans are roasted over charcoal. Also serves excellent macchiatos.',
    details_am: 'ጥሩ ቡና እየጠጡ እረፍት የሚያደርጉበት ቦታ።',
    lat: 12.6075,
    lng: 37.4690,
    address_en: 'Piazza',
    address_am: 'ፒያሳ',
    area: 'City Center',
    featured: false,
    status: Status.PUBLISHED,
    price_level: '$',
    amenities: ['Coffee Ceremony', 'Snacks', 'Local Vibes'],
    image_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    created_at: new Date().toISOString()
  }
];

export const MOCK_EVENTS: Event[] = [
  {
    id: 'e-1',
    title_en: 'Timket (Epiphany)',
    title_am: 'ጥምቀት',
    desc_en: 'Gondar’s largest festival, featuring grand religious processions.',
    desc_am: 'በጎንደር የሚከበር ታላቅ ሃይማኖታዊ በዓል።',
    start_date: '2025-01-18',
    end_date: '2025-01-20',
    lat: 12.6110,
    lng: 37.4580,
    location_name_en: 'Fasilides Bath',
    location_name_am: 'ፋሲለደስ መዋኛ',
    featured: true,
    image_url: 'https://images.unsplash.com/photo-1548013146-72479768bbaa?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'e-2',
    title_en: 'Enkutatash (Ethiopian New Year)',
    title_am: 'እንቁጣጣሽ',
    desc_en: 'Celebrated in September with yellow flowers and feasting.',
    desc_am: 'የኢትዮጵያ አዲስ ዓመት በዓል።',
    start_date: '2025-09-11',
    end_date: '2025-09-11',
    lat: 12.6072,
    lng: 37.4695,
    location_name_en: 'Fasil Ghebbi Square',
    location_name_am: 'ፋሲል ግቢ አደባባይ',
    featured: false,
    image_url: 'https://images.unsplash.com/photo-1467307983825-619715426c70?auto=format&fit=crop&w=800&q=80'
  }
];
